{
 "title": "SLURM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "总提交任务数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "slurm_submit_job_count" }
   ]
  },
  {
   "title": "队列中任务数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(slurm_squeue{JOBID!=\"JOBID\"})"
    }
   ]
  },
  {
   "title": "过去一周作业运行时间（累计）直方图",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "csv_options": {
      "delimiter": " ",
      "skip_empty_lines": true,
      "skip_lines_with_error": true
     },
     "source": "url",
     "type": "csv",
     "url": "http://192.168.1.42:9997/draw_histogram.csv",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "正在排队的任务",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "slurm_squeue{ST=\"PD\"}"
    }
   ]
  },
  {
   "title": "过去一周各组作业统计气泡图",
   "type": "ae3e-plotly-panel",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "csv_options": {
      "skip_empty_lines": true,
      "skip_lines_with_error": true
     },
     "parser": "simple",
     "source": "url",
     "type": "csv",
     "uql": "parse-csv",
     "url": "http://192.168.1.42:9998/bubble.csv",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "正在运行的任务",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "slurm_squeue{ST=\"R\"}"
    }
   ]
  }
 ]
}