{
 "title": "功耗、温度等",
 "description": "GPU dashboard for nvidia metrics ",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "所有节点",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU节点",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU节点",
    "query": {
     "query": "label_values(nvidia_gpu_num_devices,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "各节点CPU温度(℃)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_hwmon_temp_celsius{chip=~\"p.+\"}) by (chip,instance) / count(node_hwmon_temp_celsius) by (chip,instance)",
     "legendFormat": "{{instance}} - {{chip}}"
    }
   ]
  },
  {
   "title": "各CPU节点当前功耗",
   "type": "bargauge",
   "gridPos": { "h": 27, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=~\"$cpu:.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "各GPU节点当前功耗",
   "type": "bargauge",
   "gridPos": { "h": 27, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{instance=~\"$gpu:.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "各GPU卡温度（℃）",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_gpu_temperature_celsius",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "过去一个月总功耗",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(node_hwmon_power_average_watt{instance=~\"$gpu:.+\"}) by (gpu)",
     "legendFormat": "GPU节点总功耗"
    },
    {
     "expr": "sum(node_hwmon_power_average_watt{instance=~\"$cpu:9200\"}) by (cpu)",
     "legendFormat": "CPU节点总功耗"
    }
   ]
  }
 ]
}