{
 "title": "集群数据总览",
 "tags": [
  "CPU负载率",
  "以prometheus为数据源"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "数据源",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "nodename",
    "label": "主机名",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\", job=~\"$job\"}, nodename)"
    }
   },
   { "name": "head", "label": "头节点", "query": "master-1:9100,master-2:9200" },
   {
    "name": "instance",
    "label": "所有节点",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$nodename\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU节点",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",nodename=~\"$nodename\"},instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU节点",
    "query": {
     "query": "label_values(nvidia_gpu_num_devices,instance)"
    }
   },
   {
    "name": "device",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{origin_prometheus=~\"$origin_prometheus\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*'},device)"
    }
   },
   { "name": "interval", "label": "时间间隔", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "<span style=\"font-size: 36px;display:block;\">Bioland - 集群资源监控模板</span>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "各节点CPU负载率(%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_load5{instance=~\".*:9200\",instance!=\"master-2:9200\",instance!=\"master-3:9200\"})by(instance) / count(node_cpu_seconds_total{mode=\"system\",instance=~\".*:9200\",instance!=\"master-2:9200\",instance!=\"master-3:9200\"})by(instance)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "总CPU核数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode='system'})"
    }
   ]
  },
  {
   "title": "总GPU卡数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nvidia_gpu_num_devices)" }
   ]
  },
  {
   "title": "各节点内存使用率(%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=\"master-1\",instance=~\".*:9200\",instance!=\"master-2:9200\",instance!=\"master-3:9200\"} - node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=\"master-1\",instance=~\".*:9200\",instance!=\"master-2:9200\",instance!=\"master-3:9200\"}) / node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=\"master-1\",instance=~\".*:9200\",instance!=\"master-2:9200\",instance!=\"master-3:9200\"})*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "各GPU卡使用率(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "总主机数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=\"master-1\"})"
    }
   ]
  },
  {
   "title": "各GPU卡显存使用率(%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes / nvidia_gpu_memory_total_bytes * 100",
     "legendFormat": "{{instance}} - gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "总GPU显存",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_total_bytes)"
    }
   ]
  },
  {
   "title": "过去一周CPU使用情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "average_cpu_load5", "legendFormat": "CPU平均负载率" },
    { "expr": "average_memory_usage", "legendFormat": "内存平均使用率" }
   ]
  },
  {
   "title": "过去一周GPU使用情况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "average_gpu_usage", "legendFormat": "GPU平均使用率" },
    { "expr": "average_gpu_memory_usage", "legendFormat": "显存平均使用率" }
   ]
  },
  {
   "title": "CPU平均负载率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(node_load5{instance=~\".*:9200\",instance!=\"master-3:9200\",instance!=\"master-2:9200\"})by(instance) / count(node_cpu_seconds_total{mode=\"system\",instance=~\".*:9200\",instance!=\"master-3:9200\",instance!=\"master-2:9200\"})by(instance) * 100)"
    }
   ]
  },
  {
   "title": "GPU平均使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_duty_cycle) / sum(nvidia_gpu_num_devices)"
    }
   ]
  },
  {
   "title": "过去一周以太网带宽使用-头节点",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~'$head',device=\"eth2\"}[$interval])*8) by (head)",
     "legendFormat": "下载"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~'$head',device=\"eth2\"}[$interval])*8) by (head)",
     "legendFormat": "上传"
    }
   ]
  },
  {
   "title": "过去一周IB网络带宽使用",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "写入（-）/读取（+）" }
   ],
   "targets": [
    { "expr": "summary_ib_duqu", "legendFormat": "读取" },
    { "expr": "summary_ib_xieru", "legendFormat": "写入" }
   ]
  },
  {
   "title": "内存平均使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=\"master-1\",instance=~\"$cpu:.+\"} - node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=\"master-1\",instance=~\"$cpu:.+\"}) / sum(node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=\"master-1\",instance=~\"$cpu:.+\"}))*100"
    }
   ]
  },
  {
   "title": "GPU显存平均使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes) / sum(nvidia_gpu_memory_total_bytes) * 100"
    }
   ]
  }
 ]
}